on: [push]
jobs:
  pull-dataset-from-prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/_temp/Library
          key:  dependencies-v1
          
      # Getting new dataset
      - name: install requirements.txt
        env:
          SCIPY_USE_PYTHRAN: 0
        run: |
          sudo apt-get install python3-dev libpq-dev gcc libpqxx-dev libblas-dev liblapack-dev libatlas-base-dev
          pip install Cmake
          pip install -r requirements.txt
          python src/prom2csv.py
