on: [push]
jobs:
  pull-dataset-from-prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Getting new dataset
      - name: install requirements.txt
        run: |
          pip install -r requirements.txt
          python src/prom2csv.py
