on: [push]
jobs:
  pull-dataset-from-prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/_temp/Library
          key:  dependencies-v1
          
      # Getting new dataset
      - name: install requirements.txt
        env:
          SCIPY_USE_PYTHRAN: 0
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install python3-dev  python3-numpy python3-scipy libpq-dev gcc libpqxx-dev gfortran libblas3 liblapack3 liblapack-dev libblas-dev libatlas-base-dev
          pip install Cmake
          #pip install -r requirements.txt
          cd src
          python prom2csv.py
