on: [push]
jobs:
  pull-dataset-from-prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/
          key:  dependencies-v2
          
      # Installing dependencies
      - name: install requirements.txt
        env:
          SCIPY_USE_PYTHRAN: 0
        run: |
          sudo apt-get install python3-dev  python3-numpy python3-scipy libpq-dev gcc libpqxx-dev gfortran libblas3 liblapack3 liblapack-dev libblas-dev libatlas-base-dev
          pip install Cmake
          pip install -r requirements.txt
          
      # Getting new datasets
      - name: getting dataset from prometheus
        run: |
          python src/prom2csv.py
